<?php
$DB_USER = "enaboule";
$DB_PASSWORD = "dtqEb8F6xas9J4Kp";
$DB_NAME = "camgru";
$DB_DSN = "mysql:host=138.68.111.194;dbname=camgru;charset=utf8;";

try{
	$sql_co = new PDO($DB_DSN, $DB_USER, $DB_PASSWORD);
	$sql_co->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
}
catch(PDOexception $e) {
	echo $sql . "<br>" . $e->getMessage();
	die();
}
	$sql = $sql_co->prepare("CREATE TABLE IF NOT EXISTS `USERS` (
	ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	LOGIN VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	FNAME VARCHAR(50) NOT NULL,
	LNAME VARCHAR(50) NOT NULL,
	PROFILE_PICTURE MEDIUMTEXT,
	KEY_ACTIVE VARCHAR(32),
	KEY_PASSWORD VARCHAR(32),
	KEY_USERS VARCHAR(32),
	ACTIVE INT(2) DEFAULT '0',
	COMMENT TEXT,
	CREATE_DATE TIMESTAMP
);");
	echo "ABC";
	$sql->execute();
	echo "DEF";
	$sql = $sql_co->prepare("CREATE TABLE IF NOT EXISTS `PICTURES` (
		ID INT (6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
		AUTHOR_PICTURE VARCHAR(30) NOT NULL,
		IMG_DATA MEDIUMTEXT,
		KEY_PICTURES VARCHAR(32),
		KEY_USERS VARCHAR(32),
		MASK_NAME VARCHAR(32),
		CREATE_DATE_PICTURE TIMESTAMP
	);");
	$sql->execute();
	$sql = $sql_co->prepare("CREATE TABLE IF NOT EXISTS `COMMENTS` (
		ID INT (6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
		ID_PICTURES VARCHAR(150),
		KEY_USERS VARCHAR(32),
		PROFILE_PICTURE_COMMENT MEDIUMTEXT,
		AUTHOR_COMMENT VARCHAR(30) NOT NULL,
		COMMENT TEXT,
		CREATE_DATE_COMMENT TIMESTAMP
	);");
	$sql->execute();
	$sql = $sql_co->prepare("CREATE TABLE IF NOT EXISTS `LIKES` (
		ID INT (6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
		ID_PICTURES VARCHAR(150),
		AUTHOR_LIKE VARCHAR(32)
	);");
	$sql->execute();
?>
<!-- Iwm#1sbaa7
BB#lol150##mouloud
BB#123mouloud
BB#mouloud123
0f04ef23d5388a4c
b0441a9939f37932
jj9IcupqOy
jj9IeupqOy -->
<!-- JurvPMyZPfqENKjQ -->
<!-- eMdwNSJ8veCTGsyn -->
<!-- mhpdBtzEwwdqLrpL -->
<!-- 4aSqWawLMLupHDbU -->
