<?php
session_start();
if ($_SESSION['logged_in_user'] != "")
	$_SESSION['logged_in_user'] = "";
	
include 'database.php';
try{
	$sql_co = new PDO($DB_DSN, $DB_USER, $DB_PASSWORD);
	$sql_co->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
}
catch(PDOexception $e) {
	echo $sql . "<br>" . $e->getMessage();
	die();
}
	$sql = $sql_co->prepare("CREATE TABLE IF NOT EXISTS `USERS` (
	ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	LOGIN VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	FNAME VARCHAR(50) NOT NULL,
	LNAME VARCHAR(50) NOT NULL,
	PROFILE_PICTURE MEDIUMTEXT,
	KEY_ACTIVE VARCHAR(32),
	KEY_PASSWORD VARCHAR(32),
	KEY_USERS VARCHAR(32),
	ACTIVE INT(2) DEFAULT '0',
	COMMENT TEXT,
	CREATE_DATE TIMESTAMP
);");
	$sql->execute();
	$sql = $sql_co->prepare("CREATE TABLE IF NOT EXISTS `PICTURES` (
		ID INT (6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
		AUTHOR_PICTURE VARCHAR(30) NOT NULL,
		IMG_DATA MEDIUMTEXT,
		KEY_PICTURES VARCHAR(32),
		KEY_USERS VARCHAR(32),
		MASK_NAME VARCHAR(32),
		CREATE_DATE_PICTURE TIMESTAMP
	);");
	$sql->execute();
	$sql = $sql_co->prepare("CREATE TABLE IF NOT EXISTS `COMMENTS` (
		ID INT (6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
		ID_PICTURES VARCHAR(150),
		KEY_USERS VARCHAR(32),
		PROFILE_PICTURE_COMMENT MEDIUMTEXT,
		AUTHOR_COMMENT VARCHAR(30) NOT NULL,
		COMMENT TEXT,
		CREATE_DATE_COMMENT TIMESTAMP
	);");
	$sql->execute();
	$sql = $sql_co->prepare("CREATE TABLE IF NOT EXISTS `LIKES` (
		ID INT (6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
		ID_PICTURES VARCHAR(150),
		AUTHOR_LIKE VARCHAR(32)
	);");
	$sql->execute();

?>
